### ISSUE TITLE
Projecting (using ES) fails if a ReadModel is renamed or moved to another namespace

### ISSUE THREAD

**Issue by mvriel** [qandidate-labs/broadway#187] opened 2015-07-11 15:33 UTC
I have created several projections/read models and stored those in ElasticSearch using the ElasticSearch repository. Afterwards I decided to move the read models into another namespace and now the serializer fails because the class does not exist.

I have traced the issue to this location: https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/Serializer/SimpleInterfaceSerializer.php#L47

Because this is a dev environment I have emptied my ElasticSearch instance and it works again so I am afraid I can no longer capture additional information but I hope this report helps to resolve this issue. I can imagine that during a refactoring this can also happen in a production environment.

**Comment by simensen** [comment] 2015-07-11 17:44
You could consider implementing another serializer to wrap the default one that could remap the old namespace to the new one?

```php
class ClassRemappingSerializer implements SerializerInterface
{
    public function __construct(SerializerInterface $serializer, array $mapping)
    {
        $this->serializer = $serializer;
        $this->mapping = $mapping;
    }

    public function deserialize(array $serializedObject)
    {
        if (array_key_exists($serializedObject['class'], $this->mapping)) {
            $serializedObject['class'] = $this->mapping[$serializedObject['class']];
        }

        return $this->serializer->deserialize($serializedObject['class']);
    }
}
```

Then you could:

```php
$serializer = new ClassRemappingSerializer($serializer, [
    'Acme\Legacy\Event' => Acme\Newer\Event::class,
]);
```

You could make this as sophisticated as you wanted to. You could instead have custom code written to completely translate the data into into a brand new Event if instead of simply renaming the event the actual structure changed. (provided it is still compatible)

**Comment by mbadolato** [comment] 2015-07-11 18:05
> You could consider implementing another serializer to wrap the default one that could remap the old namespace to the new one?

Paul Jones just wrote a [blog entry](http://paul-m-jones.com/archives/6158) about a similar situation a few weeks ago

**Comment by mvriel** [comment] 2015-07-11 18:59
I prefer @simensen his take on this problem because class_alias injects a new class into the global scope while having a mapping inside the serializer would limit it to local scope.

So my beef with this issue is probably primarily that no 'proper' error is cast (and I understand that this was an unforeseen scenario). So would it be possible to have a mapping option in the default serializer that is passed into Symfony using the bundle and a more descriptive message if not mapped?

**Comment by simensen** [comment] 2015-07-11 19:07
I can't comment on whether the mapping belongs here. I think that the best idea would probably be to have something like this:

```php
        // add this here...
        if (! class_exists($serializedObject['class'])) {
            throw new SerializationException(
                sprintf(
                    'Class \'%s\' does cannot be instantiated because it does not exist',
                    $serializedObject['class']
                )
            );
        }

        // leave this alone...
        if (! in_array('Broadway\Serializer\SerializableInterface', class_implements($serializedObject['class']))) {
            throw new SerializationException(
                sprintf(
                    'Class \'%s\' does not implement Broadway\Serializer\SerializableInterface',
                    $serializedObject['class']
                )
            );
        }
```

This would probably make this whole thing a lot more clean *right now* and then we can try to figure out if we should add the mapping in here or just provide a `ClassRemappingSerializer` as an additional implementation that people can use *if they want to*. Maybe the Symfony bundle can be configured to use that out of the box, though?

**Comment by wjzijderveld** [comment] 2015-07-11 20:08
@mvriel we usually see read models as disposable. So this is not a use-case we addressed while developing Broadway.

I was going to suggest something similar as @simensen :-) I don't really like the `class_alias` solution either, feels way to hackish for me.

**Comment by mvriel** [comment] 2015-07-11 20:38
@wjzijderveld if that is true, then I don't get the Elasticsearch driver (which persists read models between requests) nor that replaying events to rebuild a read model is something that is not automatic; though this might be a misunderstanding from my part perhaps.

The more I think about it the more I think I missed that if you retrieve an Aggregate Root using the repository that all attached projections will be replayed; is this correct? And how does that work with a read model that is a combination of multiple instances of that aggregate root?

I get a feeling I am just missing something obvious in the equation

**Comment by wjzijderveld** [comment] 2015-07-11 21:01
No, I meant something different. I'll try to give a more elaborate answer, as I was a bit short :)

The read models are part of CQRS, it's (among others) a way to give you easier access to your last state then by just replaying the events on every request. But the events are your single source of truth. Those events are the only source of information that determine the current state.
This also means, that at any time you should be able to remove and recreate your read models. The recreating part can be tricky, depending on uptime requirements and amount of data.

But an approach you could also take, is to add a new read model, with the new name, and let is exists next to the old one. Let projectors for both read models exist and remove the old one when you don't need it anymore.

**Comment by sstok** [comment] 2015-07-13 07:31
We had some issues with the current serializer implementation.

* Not able to serialize deeper objects (unless using php `serialize()`)
* Changing the namespace or class-name breaks the replay process.

So we created our own, the plan is to share this back to the broadway project :+1: but we only need to find some time :)

**Comment by wjzijderveld** [comment] 2015-07-13 08:31
I would like to have some sort of serializer that doesn't rely on storing the classname in the database.

We faced the nested objects as well, but we simply solved that by serializing all nested objects to flat arrays as well. But I agree, that this can get annoying real quick.

**Comment by jacobkiers** [comment] 2015-07-13 20:22
We also faced the nested objects issue and we used the same solution as @wjzijderveld. Not really bothered by it, even though it is a little bit of extra work every time.

We have thought about a better solution for this (also in other projects), but have not yet found it. I have thought about using the Symfony serializer, or JSM Serializer for this. However, that adds it's own layer of complexity for - essentially - a very simple use case.

**Comment by jacobkiers** [comment] 2015-07-13 20:35
Also, I don't really think using the class name for determining different stream types as something bad. Especially since the write model is by definition the single source of truth. Only when the write model is replaced with some other implementation this might be an issue, I think.

I do not think that changing class names / namespaces is very common in production code. And if it really must be done, adding a remapper is easy, as demonstrated by @simensen.

With regards to dispatching events: as long as one stays in PHP land, it's still not an issue. And when exposed to something in a different language, I'd think one would need some kind of a mapping layer anyway.

**Comment by matthiasnoback** [comment] 2015-07-17 08:52
If you're looking for a simple serialization solution (also supports endless nesting): https://github.com/matthiasnoback/broadway-serialization :)

**Comment by mvriel** [comment] 2015-07-17 09:01
@matthiasnoback how is this relevant to this issue?

**Comment by matthiasnoback** [comment] 2015-07-17 09:24
@mvriel Maybe I was too quick - when I heard @sstok talking about nested serialization, I was just triggered to mention my library, which supports this out-of-the-box, without all the JMSSerializer/annotation/getters+setters stuff. Sorry if it doesn't apply here after all!

**Comment by mvriel** [comment] 2015-07-17 09:25
No need to apologise, I was seriously interested how it would relate to the issue since I didn't see something related to stored class names in the library :)

**Comment by sstok** [comment] 2015-07-17 09:43
As I don't have the time to work on a PR at the moment :)

We resolved the nested objects problem by always passing the Serializer service to every call of `(de)serialize()`

```php
    /**
     * @return self
     */
    public static function deserialize(array $data, SerializerInterface $serializer)
    {
        $authentication = $serializer->deserialize($data['authentication']);
        $profile = $serializer->deserialize($data['profile']);
        $authorization = $serializer->deserialize($data['authorization']);

        return new self($authentication, $profile, $authorization);
    }

    public function serialize(SerializerInterface $serializer)
    {
        return [
            'authentication' => $serializer->serialize($this->authentication),
            'profile' => $serializer->serialize($this->profile),
            'authorization' => $serializer->serialize($this->authorization),
        ];
    }
```

To prevent future name changes breaking the code, each Serializable class has a `getContractName()` which returns a unique "contract"-name for object. (idea taken from https://github.com/event-centric).

The serializer service (using a mapper service) maps the contract name to the actual class-name.
Whenever the namespace changes you only need to update the mapper or add a compatible deserializer for the legacy code.

**Comment by matthiasnoback** [comment] 2015-07-17 18:10
@sstok I would write the same code like this:
```php
/**
     * @return self
     */
    public static function deserialize(array $data)
    {
        $authentication = Authentication::deserialize($data['authentication']);
        $profile = Profile::deserialize($data['profile']);
        $authorization = Authorization::deserialize($data['authorization']);

        return new self($authentication, $profile, $authorization);
    }

    public function serialize(SerializerInterface $serializer)
    {
        return [
            'authentication' => $this->authentication->serialize(),
            'profile' => $this->profile->serialize(),
            'authorization' => $this->authorization->serialize(),
        ];
    }
```
Then you don't need the actual serializer in these functions.

As for the other problem, yes, I agree, another solution is needed to decouple the FQCN from the event type. I don't like the `getContractName()` much, since you also need it the other way around. So an actual map might make a bit more sense.

**Comment by matthiasnoback** [comment] 2015-07-17 18:11
@sstok Sorry, you said that already ;)

**Comment by sstok** [comment] 2015-07-18 10:17
The problem is (with our system) that `$authentication` is an interface and can be any object.
It can be `UsernamePasswordAuthentication` or `TokenAuthentication` (as an example, not actually using that at the moment).

**Comment by matthiasnoback** [comment] 2015-07-18 12:00
@sstok Interesting use case! I get it now :)

**Comment by sstok** [comment] 2015-07-31 11:40
I may have better idea for the serializer :)

Just return the object/array as-is and let the serializer check if its object.
If it is, serialize it. Then when deserializing you look if the value is an array, if yes then look if its an hash (array) or a serialized object.

```json
{
    "contacts": {
        "type": "hash",
        "value": [
            {
                "type": "object",
                "contract": "users.contact",
                "value": {}
            },
            {
                "type": "object",
                "contract": "users.contact",
                "value": {}
            }
        ]
    },
    "authentication": {
        "type": "object",
        "contract": "users.contact",
        "value": {}
    }
}
```

**Comment by wjzijderveld** [comment] 2015-11-30 10:18
Closing this for now, if you have more questions, or think we have distilled a more solvable issue, please reopen or create a new issue :)

**Closed by wjzijderveld** 2015-11-30 10:18 UTC
